In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[3,4,5],[5,6,7]]
np.array(my_matrix)

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [5]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [7]:
#Numpy version
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
#Gives you 3 evenly spaced numbers between 0 and 10
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(5,4)

array([[0.1014664 , 0.65060567, 0.14014453, 0.26782975],
       [0.12780382, 0.59946389, 0.21424822, 0.84007353],
       [0.67010216, 0.20745523, 0.44806437, 0.51466163],
       [0.5825774 , 0.52186603, 0.19821699, 0.60256952],
       [0.18527042, 0.72734817, 0.34777706, 0.59732496]])

In [25]:
#Random from a normal distribution
np.random.randn(5,5)

array([[-0.68641486,  3.6168909 , -0.97194407,  0.31264576,  1.35571775],
       [ 0.31836645, -0.68821331, -1.21007172,  1.84142903,  0.91178156],
       [-0.73776795, -2.17093794,  0.42600871,  0.28959707,  0.08102604],
       [ 0.64898027, -0.58481943,  0.70434347,  2.64303832,  1.12009977],
       [-0.01110022,  0.35540984, -3.06746841, -0.42260822, -0.58019292]])

In [26]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Conditional Selection**

In [27]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [30]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [31]:
arr[arr<=9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])